#!/bin/bash
set -eu

SHIELD_ETC="${SHIELD_ETC:-/etc/shield}"
PORT=${PORT:-5444}

if [[ ! -d "${SHIELD_ETC}" ]]; then
  echo >&2 "${SHIELD_ETC}/ directory not found."
  echo >&2
  echo >&2 "Perhaps you forgot to set a custom SHIELD_ETC"
  echo >&2 "environment variable..."
  exit 1
fi

if [[ -z "${SHIELD_API:-}" ]]; then
  echo >&2 "SHIELD_API not set in environment."
  echo >&2
  echo >&2 "Please set this to the full URL of your SHIELD core"
  exit 1
fi

if [[ ! -f "${SHIELD_ETC}/ssh.key" ]]; then
  ssh-keygen -m PEM -t rsa -f "${SHIELD_ETC}/ssh.key" -N ''
  rm -f "${SHIELD_ETC}/ssh.key.pub"
fi

echo "waiting for SHIELD Core to spin up on ${SHIELD_API}..."
count=240
while ! curl -Ls ${SHIELD_API}/v2/info 2>/dev/null | grep -q '"api"'; do
  sleep 1
  count=$(( count - 1 ))
  if [[ $count == 0 ]]; then
    echo >&2 "failed to find SHIELD core after 4 minutes; giving up."
    exit 2
  fi
done
curl "${SHIELD_API}/v1/meta/pubkey" >> "${SHIELD_ETC}/authorized_keys"
cat > "${SHIELD_ETC}/agent.conf" <<EOF
---
authorized_keys_file: ${SHIELD_ETC}/authorized_keys
host_key_file: ${SHIELD_ETC}/ssh.key
listen_address: 0.0.0.0:${PORT}
plugin_paths:
  - /shield/plugins

name: ${SHIELD_AGENT_NAME:-$(hostname)}
registration:
  url: ${SHIELD_API}
  interval: ${SHIELD_REGISTRATION_INTERVAL:-15}
EOF

export PATH=$PATH:/shield/bin
exec /shield/bin/shield-agent --config "${SHIELD_ETC}/agent.conf" "$@"
exit 1
