---
web-root:  /shield/ui/htdocs
data-dir:  /shield/data
plugin_paths:
  - /shield/plugins

vault:
  address: http://127.0.0.1:8200

api:
  bind: 0.0.0.0:8080
  failsafe:
    username: admin
    password: shield
