#!/bin/bash

set -e

chown -R $(whoami) .

export GOPATH=${PWD}/gopath
export PATH=${PATH}:${GOPATH}/bin

cd ${GOPATH}/src/${MODULE}

# customization - shield runs a battery of live-fire tests
# against a real shieldd + agent pair.
make shield shield-cli test
