#!/bin/bash

set -e

chown -R $(whoami) .

export GOPATH=${PWD}/gopath
export PATH=${PATH}:${GOPATH}/bin

cd ${GOPATH}/src/${MODULE}

godep restore

go vet $(go list ./... | grep -v vendor)
go test -v ./...

