---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ((concourse_go_image_repository))
    tag:        ((concourse_go_image_tag))

inputs:
- name: version
- name: git
- name: git-ci

outputs:
- name: build

run:
  path: git-ci/ci/scripts/build
