---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: registry.ops.scalecf.net/genesis-community/genesis
    tag: latest

inputs:
- name: git
- name: git-ci
- name: git-latest-tag
- name: version
- name: release-notes

outputs:
- name: release-notes

params:
  GITHUB_ACCESS_TOKEN: ((github.access_token))

run:
  path: git-ci/ci/scripts/generate-release-notes
