#!/bin/bash

rootdir=$(cd $(dirname $BASH_SOURCE[0])/.. ; pwd)

if [[ -z ${SHIELD_API} ]]; then
	echo "Missing SHIELD_API=http://... environment variable\!"
	exit 2
fi
PATH=$PATH:${rootdir}/bin

# clear stuff out
for type in target store schedule job; do
	for uuid in $(bkp -r list ${type}s | jq -r '.[].uuid'); do
		echo "Deleting ${type} $uuid"
		bkp delete ${type} $uuid
	done
done
for uuid in $(bkp -r list retention policies | jq -r '.[].uuid'); do
	echo "Deleting retention policy $uuid"
	bkp delete retention policy $uuid
done

cat <<EOF | bkp create schedule
name: Daily Backups
when: daily 3am
EOF
SCHEDULE=$(bkp -r list schedules | jq -r .[].uuid)

cat <<EOF | bkp create retention policy
name:    Default Retention
expires: 8640000
EOF
RETENTION=$(bkp -r list retention policies | jq -r .[].uuid)

cat <<EOF | bkp create store
name:     Dummy Store
plugin:   dummy
endpoint: '{"directory":"/tmp/shield/dummy"}'
EOF
STORE=$(bkp -r list stores | jq -r .[].uuid)

cat <<EOF | bkp create target
name:     Shield DB Backups
plugin:   postgres
endpoint: '{"pg_host":"localhost","pg_port":"5224","pg_user":"shieldadmin","pg_password":"admin","pg_database":"shielddb"}'
agent:    10.244.2.11:5444
EOF
TARGET=$(bkp -r list targets | jq -r .[].uuid)

cat <<EOF | bkp create job
name:      Shield DB Backups
target:    "${TARGET}"
store:     "${STORE}"
schedule:  "${SCHEDULE}"
retention: "${RETENTION}"
paused:    false
EOF
