#!/bin/bash

curly() {
	local url=$1 ; shift
	echo ${url} "$@"
	curl -Lsk http://localhost:8080${url} "$@" | tee tmp.out | jq .
	UUID=$(cat tmp.out | jq -r .uuid)
	rm tmp.out

	if [[ -z $UUID ]]; then
		echo "${url}: failed (no UUID)"
		exit 1
	fi
}

DATAROOT="/tmp/shield/dummy"
mkdir -p "${DATAROOT}"

curly /v1/targets -X POST --data-binary '{"name":"Dummy Target","summary":"Target System for testing","plugin":"dummy","endpoint":"{\"data\":\"XYZZY\"}","agent":"127.0.0.1:9090"}'
DUMMY_TARGET_UUID=$UUID

curly /v1/stores -X POST --data-binary '{"name":"Dummy Store","summary":"Store System for testing","plugin":"dummy","endpoint":"{\"directory\":\"'${DATAROOT}'\"}"}'
DUMMY_STORE_UUID=$UUID

curly /v1/schedules -X POST --data-binary '{"name":"Daily Backups","summary":"Daily Backups","when":"daily 3am"}'
DAILY_UUID=$UUID
curly /v1/schedules -X POST --data-binary '{"name":"Weekly Backups","summary":"Weekly Backups","when":"sundays at 11:30pm"}'
WEEKLY_UUID=$UUID

curly /v1/retention -X POST --data-binary '{"name":"Short-Term","summary":"Retention Policy for daily backups","expires":'$(( 86400 * 8 ))'}'
SHORT_UUID=$UUID
curly /v1/retention -X POST --data-binary '{"name":"Long-Term","summary":"Retention Policy for weekly backups","expires":'$(( 86400 * 90 ))'}'
LONG_UUID=$UUID

curly /v1/jobs -X POST --data-binary '{"name":"Test Backup","summary":"","target":"'$DUMMY_TARGET_UUID'","store":"'$DUMMY_STORE_UUID'","schedule":"'$DAILY_UUID'","retention":"'$SHORT_UUID'"}'
