#!/bin/sh
set -e

exec 1>&2
echo

export PUBLIC_PORT=${PUBLIC_PORT:-9009}
if [[ -z "${SHIELD_NO_BUILD:-}" ]]; then
  echo "» building SHIELD API OCI image…"
  docker-compose -p shield_integration_tests -f t/docker-compose.yml build
fi
echo "» (re)starting INTEGRATION TEST docker compose infrastructure…"
docker-compose -p shield_integration_tests -f t/docker-compose.yml down -v
docker-compose -p shield_integration_tests -f t/docker-compose.yml up -d
echo "» waiting for http://127.0.0.1:$PUBLIC_PORT/ to come online…"
n=300
while [[ $n != 0 ]]; do
  if curl --connect-timeout 1 -sf http://127.0.0.1:$PUBLIC_PORT/ >/dev/null; then
    exit 0
  fi
  sleep 0.1
  n=$((n - 1))
done
exit 1
