#!/bin/bash
set -e

rm -f vault vault.zip
curl -Lo vault.zip https://releases.hashicorp.com/vault/0.8.3/vault_0.8.3_linux_amd64.zip
unzip vault.zip

mkdir -pv t/travis-bin
cp -v vault t/travis-bin/
export PATH=$PATH:$(pwd)/t/travis-bin

make shield test
